### 项目过程中遇到的问题  

1. 测试指令无法运行
- 在原始虚拟机上运行测试指令`make test`报错如下:  
```
vagrant@server:/vagrant/project$ make test
···
sudo python2 -m pytest -vs -p no:warnings ./test
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/__init__.py", line 5, in <module>
    from typing import Optional
ImportError: No module named typing
Makefile:30: recipe for target 'test' failed
make: *** [test] Error 1
```
尝试安装`typing`依赖包解决, 失败：
```
vagrant@server:/vagrant/project$ pip2 install typing
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
设置locale后，重新安装`typing`依赖包成功  
```
vagrant@client:/vagrant/project$ export LC_ALL="en_US.UTF-8"
vagrant@client:/vagrant/project$ export LC_CTYPE="en_US.UTF-8"
vagrant@client:/vagrant/project$ sudo dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.

vagrant@client:/vagrant/project$ pip install typing
Collecting typing
  Downloading https://files.pythonhosted.org/packages/22/30/64ca29543375759dc589ade14a6cd36382abf2bec17d67de8481bc9814d7/typing-3.7.4.1-py2-none-any.whl
Installing collected packages: typing
Successfully installed typing
```
再次运行`make test`失败：
```
vagrant@server:/vagrant/project$ make test
mkdir -p ./build
gcc -pthread -g -ggdb -Wall -DDEBUG -I./inc ./test/testing_server.c -o ./test/testing_server ./build/cmu_packet.o ./build/cmu_tcp.o ./build/backend.o
head -c 100M </dev/urandom > ./test/random.input
sudo python2 -m pytest -vs -p no:warnings ./test
/usr/bin/python2: No module named pytest
Makefile:30: recipe for target 'test' failed
make: *** [test] Error 1
```
运行`pip install pytest`, 安装`pytest`失败：
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: pytest .dist-info directory not found
```
需升级本地pip版本, 运行`pip install --upgrade pip`，升级成功后发现运行pip报错如下:
```
vagrant@server:/vagrant/project$ pip install pytest
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```
需编辑pip运行文件，`sudo vim /usr/bin/pip`, 修改成如下内容：
```
#!/usr/bin/python
# GENERATED BY DEBIAN

import sys

# Run the main entry point, similarly to how setuptools does it, but because
# we didn't install the actual entry point from setup.py, don't use the
# pkg_resources API.
from pip import __main__
if __name__ == '__main__':
    sys.exit(__main__.main())
```
安装pytest依赖，`pip install pytest --user`，注意添加`--user`选项，安装成功  
至此，运行环境依赖配置完成  

- 环境配置完成后，运行`make test`报错如下：  
```
vagrant@client:/vagrant/project$ make test
mkdir -p ./build
gcc -pthread -g -ggdb -Wall -DDEBUG -I./inc ./test/testing_server.c -o ./test/testing_server ./build/cmu_packet.o ./build/cmu_tcp.o ./build/backend.o
head -c 100M </dev/urandom > ./test/random.input
sudo python2 -m pytest -vs -p no:warnings ./test
========================================================================= test session starts =========================================================================
platform linux2 -- Python 2.7.12, pytest-4.6.7, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /vagrant/project
collected 7 items

test/test_cp1.py::test_pcap_packets_max_size PASSED
test/test_cp1.py::test_pcap_acks PASSED
test/test_cp1.py::test_run_server_client no server running on /tmp/tmux-0/default
no server running on /tmp/tmux-0/default
FAILED
test/test_cp1.py::test_basic_reliable_data_transfer PASSED
test/test_cp1.py::test_basic_retransmit PASSED
test/test_cp1.py::test_basic_ack_packets[p] XFAIL
test/test_cp1.py::test_basic_ack_packets[pytest 1234567] XFAIL
···
        with Connection(host=TESTING_HOST_IP, user='vagrant', connect_kwargs={'password':'vagrant'}) as conn:
            try:
                conn.local(start_client_cmd)
>               conn.local('tmux has-session -t pytest_client')

test/test_cp1.py:128:
```
排查后发现测试目录路径错误，修改`test/test_cp1.py`中测试目录为`CODE_DIR = '/vagrant/project'`  
再次运行报出新错误
```
        with Connection(host=TESTING_HOST_IP, user='vagrant', connect_kwargs={'password':'vagrant'}) as conn:
            try:
                conn.local(start_client_cmd)
                conn.local('tmux has-session -t pytest_client')
>               conn.run(start_server_cmd, shell=True)

test/test_cp1.py:129:
```
排查后发现，两台虚拟机`server`与`client`无法使用ssh通过密码登陆导致问题发生，在两台虚拟机上分别修改ssh配置文件，`sudo vim /etc/ssh/sshd_config`, 将配置文件中`PasswordAuthentication`修改为yes，重新启动ssh服务`sudo service ssh restart`  
```
# Change to no to disable tunnelled clear text passwords
PasswordAuthentication yes
```

再次运行`make test`，测试终于跑通  
```
vagrant@client:/vagrant/project$ make test
mkdir -p ./build
gcc -pthread -g -ggdb -Wall -DDEBUG -I./inc ./test/testing_server.c -o ./test/testing_server ./build/cmu_packet.o ./build/cmu_tcp.o ./build/backend.o
head -c 100M </dev/urandom > ./test/random.input
sudo python2 -m pytest -vs -p no:warnings ./test
============================== test session starts ===============================
platform linux2 -- Python 2.7.12, pytest-4.6.7, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /vagrant/project
collected 7 items

test/test_cp1.py::test_pcap_packets_max_size PASSED
test/test_cp1.py::test_pcap_acks PASSED
test/test_cp1.py::test_run_server_client no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-0/default
no server running on /tmp/tmux-1000/default
PASSED
test/test_cp1.py::test_basic_reliable_data_transfer PASSED
test/test_cp1.py::test_basic_retransmit PASSED
test/test_cp1.py::test_basic_ack_packets[p] Begin emission:
Finished sending 1 packets.
*
Received 1 packets, got 1 answers, remaining 0 packets
XPASS
test/test_cp1.py::test_basic_ack_packets[pytest 1234567] Begin emission:
Finished sending 1 packets.
*
Received 1 packets, got 1 answers, remaining 0 packets
XFAIL

================ 5 passed, 1 xfailed, 1 xpassed in 10.94 seconds =================
```